### ISSUE TITLE
USB type-C and TouchPad

### ISSUE THREAD

**Issue by ghost** [ErrorErrorError/msi-gs65-8se-opencore-macos#1]
Hello!
You are really awesome, because usb-c hdmi video is work!!!
I'm delete all kexts Vodoo and replase with VoodooPS2Controller.kext
Then add USBxhci.kext for work USB-type-c and IOElectrify.kext for plug&play type-c
For fix sleep - you need add HibernationFixup.kext

[kext.zip](https://github.com/ErrorErrorError/msi-gs65-8se-opencore-macos/files/4673303/kext.zip)

**Comment by erikbdev** [comment]
The USBxhci.kext and USBPorts.kext is the exact same thing just that USBxhci.kext has no power information and has the usb port limit patch. I would not recommend using USBxhci.kext and just keep USBPorts.kext. 

Also, HibernationFixup.kext does NOT fix sleep. HibernationFixup.kext is another way to resume files/desktop ect. when it sleeps. It does not fix any sleep issues.

**Comment by dac19980925** [comment]
HibernationFixup.kext need some step to fix sleep. On my laptop, I use opencore configurator and set misc/Hibernate Mode from None to NVRAM. Now there have no sleep issue.

**Comment by handzup** [comment]
> Hello!
> 
> You are really awesome, because usb-c hdmi video is work!!!
> 
> [kext.zip](https://github.com/ErrorErrorError/msi-gs65-8se-opencore-macos/files/4673303/kext.zip)
> 
> 
@sadykovildar92 
hi, does your type c cable have any converter? (displaylink) or is it a regular type c to hdmi cable?
