### ISSUE TITLE
CPU fan speed

### ISSUE THREAD

**Issue by mark-maxwell2020** [ErrorErrorError/msi-gs65-8se-opencore-macos#5]
Your work is good enough, I enjoy it. With all due respect, 
The CPU fan is still on even temperature below 40°C，how about turning off CPU fan when the CPU temperature is below 50°C?

**Comment by erikbdev** [comment]
> Your work is good enough, I enjoy it. With all due respect,
> The CPU fan is still on even temperature below 40°C，how about turning off CPU fan when the CPU temperature is below 50°C?

I haven't done any research on controlling fan speed. It might be involving having to edit fans speed on the DSDT.aml.

**Comment by mark-maxwell2020** [comment]
All right. Looking forward to your new research on that.

**Comment by erikbdev** [comment]
> All right. Looking forward to your new research on that.

I'm not planning on investigating how to control fans speeds however if you would like to share more on how you got it to work, if you ever get it to work since it might not just affect macOS but also windows/linux,  you can always open this issue.
