### ISSUE TITLE
SMBIOS & Big Sur performance 

### ISSUE THREAD

**Issue by handzup** [ErrorErrorError/msi-gs65-8se-opencore-macos#7]
Thanks for the amazing job!
have you done performance tests in geekbench? after switching to big sur, my results dropped significantly and I don't know what this might be due to
Catalina had single -core 912 multi -core 4179
on big sur single -core 736 multi -core 3582
By the way, I noticed that on your EFI clover my hackintosh was identified as macbookpro 15.2 and now it shows as macbookpro 13, I could not generate S / N for macbookpro15.2, have any ideas on this?
thanks again!

**Comment by erikbdev** [comment]
> have you done performance tests in geekbench? after switching to big sur, my results dropped significantly and I don't know what this might be due to

I haven't done any performance test unfortunately.

> By the way, I noticed that on your EFI clover my hackintosh was identified as macbookpro 15.2 and now it shows as macbookpro 13, I could not generate S / N for macbookpro15.2, have any ideas on this?

You should use [Dortaria](https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html) to generate a SMBios using MacBookPro15,2.

**Comment by handzup** [comment]
Thank you so much for your answer
but about mac shows that I have a 13 inch macbookpro
![photo_2020-12-16_04-03-29](https://user-images.githubusercontent.com/23139753/102691171-670f9200-422c-11eb-87e8-bb57dd0889ad.jpg)

I have additional problems :) I use multiboot, my Windows and MacOS are on separate disks and I have one EFI partition for them. The problem is that booting into Windows via OpenCore breaks SMBIOS for windows showing that I am using mac and because of this having problems with dragoncenter
Windows msinfo shows i'm using macbook pro
![dgcenter](https://user-images.githubusercontent.com/23139753/102691006-39761900-422b-11eb-9603-740aedc65424.PNG)
![msinfo32](https://user-images.githubusercontent.com/23139753/102690973-eac87f00-422a-11eb-854d-df57aec68c62.png)
But when loading into windows through a selection from the boot menu, everything works fine and the windows recognize that I have msi gs65

**Comment by mark-maxwell2020** [comment]
> Thanks for the amazing job!
> have you done performance tests in geekbench? after switching to big sur, my results dropped significantly and I don't know what this might be due to
> Catalina had single -core 912 multi -core 4179
> on big sur single -core 736 multi -core 3582
> By the way, I noticed that on your EFI clover my hackintosh was identified as macbookpro 15.2 and now it shows as macbookpro 13, I could not generate S / N for macbookpro15.2, have any ideas on this?
> thanks again!

i7 8750H, geekbench 5. Catalina 10.15.7 had single -core 803 multi -core 3956

**Comment by erikbdev** [comment]
> But when loading into windows through a selection from the boot menu, everything works fine and the windows recognize that I have msi gs65

The reason for this is OpenCore is designed to simulate a macOS computer, so it basically works the same way if a real mac was booting to windows. You can change this however by replacing `UpdateSMBIOSMode` string value to `Custom` in config.plist.

**Comment by handzup** [comment]
@ErrorErrorError Thanks, I'll try as you said

**Comment by handzup** [comment]
> > But when loading into windows through a selection from the boot menu, everything works fine and the windows recognize that I have msi gs65
> 
> The reason for this is OpenCore is designed to simulate a macOS computer, so it basically works the same way if a real mac was booting to windows. You can change this however by replacing `UpdateSMBIOSMode` string value to `Custom` in config.plist.

CustomSMBIOSGuid = Yes and UpdateSMBIOSMode = Custom
OpenCore will not change smbios for non-macOS.

**Comment by oldman20** [comment]
> > > But when loading into windows through a selection from the boot menu, everything works fine and the windows recognize that I have msi gs65
> > 
> > 
> > The reason for this is OpenCore is designed to simulate a macOS computer, so it basically works the same way if a real mac was booting to windows. You can change this however by replacing `UpdateSMBIOSMode` string value to `Custom` in config.plist.
> 
> CustomSMBIOSGuid = Yes and UpdateSMBIOSMode = Custom OpenCore will not change smbios for non-macOS.

but OC still inject acpi into other OSes if not using OC mod no-acpi or edit *.aml with key **If (Darwin)**
